---
roles:
  - name: geerlingguy.nginx
    version: latest
  - name: community.postgresql
    version: latest
  - name: community.general
    version: latest
  - name: rvm.ruby
    version: latest
  - name: ansible.posix
